<?php

namespace wpdanceclaratheme\htmlblock;


###########################################################################
# DEFINE WP HOOKS
###########################################################################


add_action('wp_enqueue_scripts', __NAMESPACE__.'\\enqueue_scripts');
add_action('wp_head', __NAMESPACE__.'\\wp_head');



###########################################################################
# DEFINE WP FILTERS
###########################################################################

add_filter('body_class', __NAMESPACE__.'\\body_class', 10, 1);




###########################################################################
# DEFINE HOOK CALLBACK FUNCTIONS
###########################################################################

if (!function_exists(__NAMESPACE__.'\\wp_head')):
/**
 * Callback function for WP Hook 'wp_head'
 */
function wp_head() {

	/**
	 * Add custom CSS of header & footer posts into head tab
	 *
	 * Custom CSS is generated by Visual Composer plugin. Visual Composer 
	 * only includes css style of the main post, so we have to add custom css 
	 * styles of HTML blocks by ourself.
	 */

	if (function_exists('visual_composer') && function_exists('\\wpdance\\Plugins\\htmlblock\\get_css')) {
		if ($post = \wpdanceclaratheme\Helper\get_header_post())
			echo \wpdance\Plugins\htmlblock\get_css($post->ID);
			
		if ($post = \wpdanceclaratheme\Helper\get_footer_post())
			echo \wpdance\Plugins\htmlblock\get_css($post->ID);
	}
}
endif;




if (!function_exists(__NAMESPACE__.'\\enqueue_scripts')):
/**
 * Hook to enqueue scripts & styles output by VC shortcodes
 * 
 * @return [type] [description]
 */
function enqueue_scripts() {
	# Call this functions so that VC shortcodes print style/script to <head>
	# vc_google_fonts_
	\wpdanceclaratheme\Helper\get_header();
	\wpdanceclaratheme\Helper\get_footer();
}
endif;


###########################################################################
# DEFINE FILTER CALLBACK FUNCTIONS
###########################################################################


/**
 * Callback function for filter 'body_class', add CSS class for determizing html block used
 * 
 * @param  array $classes
 * @return array
 */
function body_class($classes) {
	if (!is_array($classes)) $classes = array($classes);

	if ($post = \wpdanceclaratheme\Helper\get_header_post())
		$classes[] = $post->post_name;

	if ($post = \wpdanceclaratheme\Helper\get_footer_post())
		$classes[] = $post->post_name;

	return $classes;
}






