<?php
/**
 * Visual Composer plugin integration
 */

namespace wpdanceclaratheme\VC;

# Stop if Visual Composer is activated
if (!function_exists('visual_composer')) return;

add_action('wp_footer', __NAMESPACE__.'\\wp_footer');
add_filter('style_loader_tag', __NAMESPACE__.'\\fix_footer_link_tags', 10, 4);

add_filter('vc_shortcode_output', __NAMESPACE__.'\\fix_img_no_alt', 10, 3);


if (!function_exists(__NAMESPACE__.'\\wp_footer')):
function wp_footer() {
	Data::$footer = true;
}
endif;


if (!function_exists(__NAMESPACE__.'\\fix_footer_link_tags')):
/**
 * Filter 'style_loader_tag' to move all <link> generated by VC Shortcodes to <head> using js
 * for W3C HTML validation
 * 
 * @param  [type] $content [description]
 * @param  [type] $handle  [description]
 * @param  [type] $href    [description]
 * @param  [type] $media   [description]
 * @return [type]          [description]
 */
function fix_footer_link_tags($content, $handle, $href, $media) {

	# Fix media='' invalidate HTML
	if (!$media)
		$content = str_replace("media=''", "media='screen'", $content);

	if (!Data::$footer || strpos($handle, 'vc_') !== 0 && strpos($href, 'js_composer') === false)
		return $content;

	$html = json_encode($content);
	$s = <<<EOB
	<script type="text/javascript">
	// <![[CDATA
	jQuery(function($) {
		'use strict';
		$('head').append($html);
	});
	// ]]>
	</script>
EOB;
	return $s;
}
endif;


function fix_img_no_alt($content, $obj, $atts) {
	if ($obj instanceof \WPBakeryShortCode_VC_Single_image) {
		if (!preg_match('#<img[^>]+alt=#miu', $content)) {
			$alt = esc_html(isset($atts['caption']) && !empty($atts['caption']) ? $atts['caption'] : (isset($atts['title']) && !empty($atts['title']) ? $atts['title'] : ''));
			$content = preg_replace('#<img((?:(?!:alt=).)+)/>#msiuU', '<img\\1 alt="'.esc_attr($alt).'" />', $content);
		}
	}
	return $content;
}


if (!class_exists(__NAMESPACE__.'\\Data')):
/**
 * Class to hold variables inside the namespace to avoid using global vars
 */
class Data {
	static $footer = false;
}
endif;